# Generated by Django 5.2.4 on 2025-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpoadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('is_ai', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
